//////////////////////////////////////////////////////////////////////////////
// Model: game.qm
// File:  ./qm_code/mine2.cpp
//
// This file has been generated automatically by QP Modeler (QM).
// DO NOT EDIT THIS FILE MANUALLY.
//
// Please visit www.state-machine.com/qm for more information.
//////////////////////////////////////////////////////////////////////////////
#include "qp_port.h"
#include "bsp.h"
#include "game.h"

Q_DEFINE_THIS_FILE

// encapsulated delcaration of the Mine2 HSM ---------------------------------
// $(AOs::Mine2) .............................................................
class Mine2 : public QHsm {
private:
    uint8_t m_x;
    uint8_t m_y;
    uint8_t m_exp_ctr;

public:
    Mine2() : QHsm((QStateHandler)&Mine2::initial) {
    }

protected:
    static QState initial(Mine2 *me, QEvent const *e);
    static QState unused(Mine2 *me, QEvent const *e);
    static QState used(Mine2 *me, QEvent const *e);
    static QState planted(Mine2 *me, QEvent const *e);
    static QState exploding(Mine2 *me, QEvent const *e);
};

// local objects -------------------------------------------------------------
static Mine2 l_mine2[GAME_MINES_MAX];                // a pool of type-2 mines

                                // helper macro to provide the ID of this mine
#define MINE_ID(me_)    ((me_) - l_mine2)

//............................................................................
QHsm *Mine2_getInst(uint8_t id) {
    Q_REQUIRE(id < GAME_MINES_MAX);
    return &l_mine2[id];
}
// Mine2 class definition ----------------------------------------------------
// $(AOs::Mine2) .............................................................

// $(AOs::Mine2::Statechart) .................................................
// @(/2/4/4/0)
QState Mine2::initial(Mine2 *me, QEvent const *e) {
    static uint8_t dict_sent;
    if (!dict_sent) {
        // object dictionaries for Mine2 pool...
        QS_OBJ_DICTIONARY(&l_mine2[0]);
        QS_OBJ_DICTIONARY(&l_mine2[1]);
        QS_OBJ_DICTIONARY(&l_mine2[2]);
        QS_OBJ_DICTIONARY(&l_mine2[3]);
        QS_OBJ_DICTIONARY(&l_mine2[4]);

        // function dictionaries for Mine2 HSM...
        QS_FUN_DICTIONARY(&Mine2::initial);
        QS_FUN_DICTIONARY(&Mine2::unused);
        QS_FUN_DICTIONARY(&Mine2::used);
        QS_FUN_DICTIONARY(&Mine2::planted);
        QS_FUN_DICTIONARY(&Mine2::exploding);

        dict_sent = 1;
    }

    // local signals...
    QS_SIG_DICTIONARY(MINE_PLANT_SIG,    me);
    QS_SIG_DICTIONARY(MINE_DISABLED_SIG, me);
    QS_SIG_DICTIONARY(MINE_RECYCLE_SIG,  me);
    QS_SIG_DICTIONARY(SHIP_IMG_SIG,      me);
    QS_SIG_DICTIONARY(MISSILE_IMG_SIG,   me);
    return Q_TRAN(&Mine2::unused);
}
// $(AOs::Mine2::Statechart::unused) .........................................
QState Mine2::unused(Mine2 *me, QEvent const *e) {
    switch (e->sig) {
        // @(/2/4/4/1/0)
        case MINE_PLANT_SIG: {
            me->m_x = ((ObjectPosEvt const *)e)->x;
            me->m_y = ((ObjectPosEvt const *)e)->y;
            return Q_TRAN(&Mine2::planted);
        }
    }
    return Q_SUPER(&QHsm::top);
}
// $(AOs::Mine2::Statechart::used) ...........................................
QState Mine2::used(Mine2 *me, QEvent const *e) {
    switch (e->sig) {
        // @(/2/4/4/2)
        case Q_EXIT_SIG: {
            // tell the Tunnel that this mine is becoming disabled
            MineEvt *mev = Q_NEW(MineEvt, MINE_DISABLED_SIG);
            mev->id = MINE_ID(me);
            AO_Tunnel->postFIFO(mev);
            return Q_HANDLED();
        }
        // @(/2/4/4/2/0)
        case MINE_RECYCLE_SIG: {
            return Q_TRAN(&Mine2::unused);
        }
    }
    return Q_SUPER(&QHsm::top);
}
// $(AOs::Mine2::Statechart::used::planted) ..................................
QState Mine2::planted(Mine2 *me, QEvent const *e) {
    switch (e->sig) {
        // @(/2/4/4/2/1/0)
        case TIME_TICK_SIG: {
            // @(/2/4/4/2/1/0/0)
            if (me->m_x >= GAME_SPEED_X) {
                ObjectImageEvt *oie;

                me->m_x -= GAME_SPEED_X; // move the mine 1 step

                // tell the Tunnel to draw the Mine
                oie = Q_NEW(ObjectImageEvt, MINE_IMG_SIG);
                oie->x   = me->m_x;
                oie->y   = me->m_y;
                oie->bmp = MINE2_BMP;
                AO_Tunnel->postFIFO(oie);
                return Q_HANDLED();
            }
            // @(/2/4/4/2/1/0/1)
            else {
                return Q_TRAN(&Mine2::unused);
            }
        }
        // @(/2/4/4/2/1/1)
        case SHIP_IMG_SIG: {
            uint8_t x = (uint8_t)((ObjectImageEvt const *)e)->x;
            uint8_t y = (uint8_t)((ObjectImageEvt const *)e)->y;
            uint8_t bmp = (uint8_t)((ObjectImageEvt const *)e)->bmp;
            // @(/2/4/4/2/1/1/0)
            if (do_bitmaps_overlap(MINE2_BMP, me->m_x, me->m_y, bmp, x, y)) {
                // Hit event with the type of the Mine2
                static MineEvt const mine2_hit(HIT_MINE_SIG, 2);
                AO_Ship->postFIFO(&mine2_hit);

                // go straight to 'disabled' and let the Ship do the exploding
                return Q_TRAN(&Mine2::unused);
            }
            break;
        }
        // @(/2/4/4/2/1/2)
        case MISSILE_IMG_SIG: {
            uint8_t x = (uint8_t)((ObjectImageEvt const *)e)->x;
            uint8_t y = (uint8_t)((ObjectImageEvt const *)e)->y;
            uint8_t bmp = (uint8_t)((ObjectImageEvt const *)e)->bmp;
            // @(/2/4/4/2/1/2/0)
            if (do_bitmaps_overlap(MINE2_MISSILE_BMP,
me->m_x, me->m_y, bmp, x, y)) {
                // test for incoming Missile hitting this mine
                // NOTE: Mine type-2 is nastier than Mine type-1.
                // The type-2 mine can hit the Ship with any of its
                // "tentacles". However, it can be destroyed by the
                // Missile only by hitting its center, defined as
                // a smaller bitmap MINE2_MISSILE_BMP.

                // Score event with the score for destroying Mine2
                static ScoreEvt const mine2_destroyed(DESTROYED_MINE_SIG, 45);
                AO_Missile->postFIFO(&mine2_destroyed);
                return Q_TRAN(&Mine2::exploding);
            }
            break;
        }
    }
    return Q_SUPER(&Mine2::used);
}
// $(AOs::Mine2::Statechart::used::exploding) ................................
QState Mine2::exploding(Mine2 *me, QEvent const *e) {
    switch (e->sig) {
        // @(/2/4/4/2/2)
        case Q_ENTRY_SIG: {
            me->m_exp_ctr = 0;
            return Q_HANDLED();
        }
        // @(/2/4/4/2/2/0)
        case TIME_TICK_SIG: {
            // @(/2/4/4/2/2/0/0)
            if ((me->m_x >= GAME_SPEED_X) && (me->m_exp_ctr < 15)) {
                ObjectImageEvt *oie;

                ++me->m_exp_ctr; // advance the explosion counter
                me->m_x -= GAME_SPEED_X; // move explosion by 1 step

                // tell the Game to render the current stage of Explosion
                oie = Q_NEW(ObjectImageEvt, EXPLOSION_SIG);
                oie->x   = me->m_x + 1; // x of explosion
                oie->y   = (int8_t)((int)me->m_y - 4 + 2); // y of explosion
                oie->bmp = EXPLOSION0_BMP + (me->m_exp_ctr >> 2);
                AO_Tunnel->postFIFO(oie);
                return Q_HANDLED();
            }
            // @(/2/4/4/2/2/0/1)
            else {
                return Q_TRAN(&Mine2::unused);
            }
        }
    }
    return Q_SUPER(&Mine2::used);
}

