QP/C++: QEP Class Reference
QEP Class Reference
Provides miscellaneous QEP services.
#include <qep.h>
Static Public Member Functions
static char const Q_ROM *Q_ROM_VAR getVersion (void)
get the current QEP version number string
Detailed Description
Provides miscellaneous QEP services.
Definition at line 42 of file qep.h.
Member Function Documentation
char const Q_ROM *Q_ROM_VAR QEP::getVersion (void) [static]
get the current QEP version number string
Returns:
version of the QEP as a constant 6-character string of the form x.y.zz, where x is a 1-digit major version number, y is a 1-digit minor version number, and zz is a 2-digit release number.
Definition at line 20 of file lint_qep.txt.
References QHsm::dispatch(), QFsm::dispatch(), QHsm::init(), QFsm::init(), QHsm::isIn(), Q_ALLEGE, Q_ASSERT, Q_DEFINE_THIS_MODULE, Q_ENTRY_SIG, Q_EXIT_SIG, Q_RET_TRAN, QEP_EMPTY_SIG_, QEP_ENTER_, QEP_EXIT_, QEP_MAX_NEST_DEPTH_, QEP_TRIG_, QP_VERSION, QS_BEGIN_, QS_FUN_, QS_OBJ_, QS_QEP_DISPATCH, QS_QEP_INIT_TRAN, QS_QEP_STATE_INIT, QS_QEP_TRAN, QS_SIG_, QEvent::sig, QS::smObj_, QHsm::top(), QFsm::~QFsm(), and QHsm::~QHsm().
The documentation for this class was generated from the following files:
qep.h
lint_qep.txt
qep.cpp